### ISSUE TITLE
BUG: Jobs using `ensure_pkg_manager` failing when relying on default `npm` or `pnpm versions`

### ISSUE THREAD

**Issue by kronicker** [ExtensionEngine/pipeline-core-orb#32]
# Bug

## Issue Description

When relying on default pkg manager versions which should be `latest` for `pnpm` or aligned w/ Node version for `npm` command `ensure_pkg_manager` is failing. 

## Steps to Reproduce

Example code for reproducing:
```yml
orbs:
  core: studion/core@2.0.1

jobs:
  run-with-pnpm:
    executor: core/node_secrets
    steps:
      - checkout
      - core/install_dependencies:
          pkg_manager: pnpm
  run-with-npm:
    executor: core/node_secrets
    steps:
      - checkout
      - core/install_dependencies

workflows:
  reproduce-issue-workflow:
    jobs:
      - run-with-pnpm
      - run-with-npm
```

## Expected Behavior

Describe what you expected to happen.
- Commands are passing and using pkg manager versions as described in the [docs](https://github.com/ExtensionEngine/pipeline-core-orb/blob/v2.0.1/src/commands/ensure_pkg_manager.yml#L9)

### Actual Behavior

Here are the screenshots:

| run-with-pnpm   |      run-with-npm       |
|----------|:-------------:|
| ![Image](https://github.com/user-attachments/assets/c0fde73c-a067-4eee-a87a-c43dbb1327f9) | ![Image](https://github.com/user-attachments/assets/9ec8b95b-8ebd-4db5-8546-49a79aff8f0e) |
